#!/bin/bash
set -e

URL="/infobases/WebCommonInfoBases"

echo Content-Type: application/json;charset=utf-8
echo Cache-Control: no-cache
echo
echo {\"root\": {\"InfoBasesChanged\": \"true\", \"URL\": \""$URL"\"}}
